services:
  - type: web
    name: dormie
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: cd backend && npm install --legacy-peer-deps && node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/students